# environment-ci.yml: Additional dependencies to install in the CI environment.
channels:
- conda-forge
- nodefaults
dependencies:
- jupyter-book=0.15.1
- make
- matplotlib
- mypy
- netCDF4
- pandas-stubs
- pooch
- pre-commit
- pytest
- pytest-cov
- tqdm
- zarr
- cartopy
- xgcm
